# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange( 0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] =100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
slice_of_arr =arr[0:6]

In [12]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
#numpy doesnot save the copy directly , so better use copy

# 2d-Array

In [18]:
arr_2d =np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[0][0] ##row and clum

5

In [21]:
arr_2d[0]#whle row

array([ 5, 10, 15])

In [23]:
arr_2d[2][2] #2nd row third column =//output =45

45

In [25]:
arr_2d[1,2] #same indexing but better  with comma

30

In [26]:
arr_2d[:2,1:] #everything upto row 2 and grab from column 1 onwards

array([[10, 15],
       [25, 30]])

# conditional selection

In [28]:
arr=np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
bool_arr= arr >5

In [33]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr] #only outputs  the true 

array([ 6,  7,  8,  9, 10])

In [37]:
arr[arr>5]#same as above

array([ 6,  7,  8,  9, 10])

In [39]:
arr_2d = np.arange(50).reshape(5,10) # create 5*10 matrix 

In [40]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
#output = #[12,13
           # 22,23]

In [57]:
arr_2d[1:3,2:4]#GET 2ND  AND tHIRD COLUMN

array([[12, 13],
       [22, 23]])

# NumPy Operations

Array with Array

In [61]:
arr =np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr+ arr #Add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
arr * arr # Multiple

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [66]:
arr *2  #with scalar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Some important Functions

In [70]:
arr / arr #erro in 0/0, but also provide the results with warning

/tmp/ipykernel_168332/1572231908.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr #erro in 0/0, but also provide the results with warning


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/ arr

/tmp/ipykernel_168332/3009366600.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [72]:
arr ** 2 #expntinal

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Universal Operations

In [73]:
np.sqrt(arr) # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [75]:
np.max(arr) #maximun

10

In [76]:
np.sin(arr) #trignometric

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
np.log(arr)

/tmp/ipykernel_168332/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#other documentaion on Numpy in documentation